### Импорты

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
from pathlib import Path

root_path = Path.cwd().parent
if str(root_path) not in sys.path:
    sys.path.append(str(root_path))

In [3]:
import numpy as np
import pandas as pd

from pathlib import Path
from src.multiple_datasets_constructor import build_multiple_datasets

### Глобальные константы

In [4]:
dataset_folder_path = Path("./data/Dunnhumby")
dataset_path = dataset_folder_path / "outflow_data.csv"

files_folder_path = Path("./data/files")

In [5]:
WINDOW_SIZE = 5

### Построение датасета

In [6]:
outflow_data = pd.read_csv(dataset_path)

In [7]:
outflow_data

,DAY,household_key,TOTAL CATEGORY,QUANTITY,WEIGHT_GR,VOLUME_ML,COUNT,SESSION_ID
0,221,766,ALMONDS,1,453.59,0.0,0.0,2
1,263,766,ALMONDS,1,453.59,0.0,0.0,2
2,281,766,ALMONDS,1,453.59,0.0,0.0,2
3,295,766,ALMONDS,1,453.59,0.0,0.0,2
4,306,766,ALMONDS,1,453.59,0.0,0.0,2
...,...,...,...,...,...,...,...,...
412101,318,2322,ZUCCHINI,1,8164.62,0.0,0.0,1
412102,347,2322,ZUCCHINI,1,8164.62,0.0,0.0,1
412103,362,2322,ZUCCHINI,1,8164.62,0.0,0.0,1
412104,380,2322,ZUCCHINI,1,8164.62,0.0,0.0,1
412105,402,2322,ZUCCHINI,1,8164.62,0.0,0.0,1

In [8]:
datasets = build_multiple_datasets(outflow_data, window_size=WINDOW_SIZE, datasets_proportions=[0.7, 0.15, 0.15], random_state=42)

Building dataset: 1

Building dataset: 100%|██████████████████████████████████| 15290/15290 [04:49<00:00, 52.74session/s]

Building dataset: 2

Building dataset: 100%|████████████████████████████████████| 3276/3276 [01:12<00:00, 45.48session/s]

Building dataset: 3

Building dataset: 100%|████████████████████████████████████| 3277/3277 [00:51<00:00, 63.26session/s]

In [9]:
X_train, y_train = datasets[0]
X_val, y_val = datasets[1]
X_test, y_test = datasets[2]

In [10]:
X_train.shape, X_val.shape, X_test.shape

((258135, 52), (55807, 52), (54478, 52))

In [11]:
X_train["target"] = y_train
X_val["target"] = y_val
X_test["target"] = y_test

In [12]:
X_train.to_csv(dataset_folder_path / "dataset_train.csv", index=False)
X_val.to_csv(dataset_folder_path / "dataset_val.csv", index=False)
X_test.to_csv(dataset_folder_path / "dataset_test.csv", index=False)

In [13]:
X_train.shape, X_val.shape, X_test.shape

((258135, 53), (55807, 53), (54478, 53))

In [14]:
X_train

,day_of_week,session_step,current_quantity,current_weight,current_volume,current_count,mean_interval,std_interval,ema_interval,rolling_mean_interval,...,norm_interval_lag_5,quantity_to_mean_ratio,baseline_pred_by_quantity,weight_to_mean_ratio,baseline_pred_by_weight,volume_to_mean_ratio,baseline_pred_by_volume,count_to_mean_ratio,baseline_pred_by_count,target
0,4.0,2.0,1.0,453.59,0.0,0.0,42.000000,-1.000000,42.000000,42.000000,...,-1.000000,1.0,42.000000,1.0,42.000000,1.0,-1.0,1.0,-1.0,18
1,1.0,3.0,1.0,453.59,0.0,0.0,30.000000,12.000000,30.000000,30.000000,...,-1.000000,1.0,30.000000,1.0,30.000000,1.0,-1.0,1.0,-1.0,14
2,1.0,4.0,1.0,453.59,0.0,0.0,24.666667,12.364825,22.000000,24.666667,...,-1.000000,1.0,24.666667,1.0,24.666667,1.0,-1.0,1.0,-1.0,11
3,5.0,5.0,1.0,453.59,0.0,0.0,21.250000,12.234684,16.500000,21.250000,...,-1.000000,1.0,21.250000,1.0,21.250000,1.0,-1.0,1.0,-1.0,13
4,4.0,6.0,1.0,453.59,0.0,0.0,19.600000,11.429786,14.750000,19.600000,...,2.142857,1.0,19.600000,1.0,19.600000,1.0,-1.0,1.0,-1.0,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258130,2.0,24.0,1.0,8164.62,0.0,0.0,22.086957,11.424280,23.916918,18.800000,...,0.407480,1.0,22.086957,1.0,22.086957,1.0,-1.0,1.0,-1.0,41
258131,1.0,25.0,1.0,8164.62,0.0,0.0,22.875000,11.805057,32.458459,25.200000,...,1.005464,1.0,22.875000,1.0,22.875000,1.0,-1.0,1.0,-1.0,13
258132,0.0,26.0,1.0,8164.62,0.0,0.0,22.480000,11.727301,22.729230,23.200000,...,0.578292,1.0,22.480000,1.0,22.480000,1.0,-1.0,1.0,-1.0,33
258133,5.0,27.0,1.0,8164.62,0.0,0.0,22.884615,11.676165,27.864615,27.200000,...,0.742857,1.0,22.884615,1.0,22.884615,1.0,-1.0,1.0,-1.0,27
258134,4.0,28.0,1.0,8164.62,0.0,0.0,23.037037,11.484229,27.432307,29.200000,...,1.389068,1.0,23.037037,1.0,23.037037,1.0,-1.0,1.0,-1.0,35